
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: metrics.iter8.tools
spec:
  group: iter8.tools
  names:
    kind: Metric
    listKind: MetricList
    plural: metrics
    singular: metric
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.type
      name: type
      type: string
    - jsonPath: .spec.description
      name: description
      type: string
    name: v2alpha2
    schema:
      openAPIV3Schema:
        description: Metric is the Schema for the metrics API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MetricSpec defines the desired state of Metric
            properties:
              description:
                description: Text description of the metric
                type: string
              params:
                description: Params are key/value pairs used to construct a REST query
                  to the metrics backend
                items:
                  description: Param name/value to be used in constructing a REST
                    query to backend metrics server
                  properties:
                    name:
                      description: Name of parameter
                      type: string
                    value:
                      description: Value of parameter
                      type: string
                  required:
                  - name
                  - value
                  type: object
                type: array
              provider:
                description: Provider identifies the metric backend including its
                  authentication properties and its unmarshaller
                minLength: 1
                type: string
              sampleSize:
                description: SampleSize is a reference to a counter metric resource.
                  It needs to indicte the number of data points over which this metric
                  is computed.
                properties:
                  name:
                    description: Name is the name of the metric
                    minLength: 1
                    type: string
                  namespace:
                    description: Namespace is the namespace where the metric is defined
                      If not provided, it is assumed to be in the same namespace as
                      the referrer.
                    type: string
                required:
                - name
                type: object
              type:
                default: gauge
                description: Type of the metric
                enum:
                - counter
                - gauge
                type: string
              units:
                description: Units used for display only
                type: string
            required:
            - provider
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
